### ISSUE TITLE
Separate delays for opening/closing

### ISSUE THREAD

**Issue by drewcovi** [krlaframboise/Hubitat#3]
https://github.com/krlaframboise/Hubitat/blob/fd729084fd7af507290fae75db68bdd25160688d/apps/zooz/zooz-garage-door-opener-app.src/zooz-garage-door-opener-app.groovy#L113

Hello! Any chance we can have separate delays for opening and closing? Or can we perhaps ignore the delay on manual close? Many put the tilt sensor high on the door which allows quick response when opening the door. However based on existing code, I'm seeing the same delay applied as the door closes, and when the sensor is at the top, this amounts to a 10-15 second delay well after the door is closed.

**Comment by drewcovi** [comment]
(I could also probably submit a pull request, so hang tight) 😄

**Comment by krlaframboise** [comment]
I don't accept pull requests...
